version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - local.env
    volumes:
    - .:/ExanteDataBackend
    restart: always
  db:
    image: postgres:14-alpine
    env_file:
      - local.env
    restart: always