version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
